name: war-routine
build_systems:
  love:
    dependencies:
    - container
    - decorator
    - exception
    - fnl
    - gamera
    - lambda
    - limited
    - log
    - module
    - tesound
    - tk
    - vector
    - inspect
    - tiny
    - strong
version: 0.3-35
